### ISSUE TITLE
Use BBB Via Laravel Facade

### ISSUE THREAD

**Issue by IbrahemElanany** [nguyenducdn87/laravel-bigbluebutton#1]
I made a controller in laravel project with that syntax :

namespace App\Http\Controllers;

use DucNguyen\Bigbluebutton\Contracts\Meeting;
use Illuminate\Http\Request;

class MeetingController extends Controller
{
    public function index()
    {
        $meetings = Meeting::all();
        dd($meetings);
    }
}

i tried to run the project but i faced this exception :
**Non-static method DucNguyen\Bigbluebutton\Contracts\Meeting::all() cannot be called statically**

**Please if you can explain more of how to use this package with laravel**
Regards ,

**Comment by nguyenducdn87** [comment]
@IbrahemElanany you can fix flow :
namespace App\Http\Controllers;

use DucNguyen\Bigbluebutton\Contracts\Meeting;
class MeetingController extends Controller
{
   /**
   * @var \DucNguyen\Bigbluebutton\Contracts\Meeting
   */
  protected $livestream;

  public function __construct(Meeting $livestream)
  {
    $this->livestream = $livestream;
  }
  public function index()
{
$meetings = $this->livestream::all();
dd($meetings);
}
}
